### ISSUE TITLE
PDE Target Platform configuration.

### ISSUE THREAD

**Issue by bruno-medeiros** [eclipselabs/eclipse-language-service#1]
So, I can build eclipse-language-service from Maven fine, but now I wanted to try it out, running hosted from the Eclipse IDE, for which I need a Target Platform. Is there an easy way to set this up? I know the `ls-api` dependencies are in `repository\target\repository`, but I couldn't figure out which p2 repo contains `org.eclipse.json`, neither http://download.eclipse.org/releases/neon nor the latest Orbit repository seems to have it.

**Comment by bruno-medeiros** [comment]
Oh, found it, it was in the WST JSON Core feature. I forgot that just searching for "org.eclipse.json" in the repository (in the target platform editor) doesn't work...

**Comment by mickaelistria** [comment]
The TP editor only shows features, that's why you couldn't see org.eclipse.json.
Once you have a TP working, it would be nice if you could contribute it to this repo and configure build to use it rather than defining repos in pom.xml . A .target file is much more contribution friendly.

**Comment by mickaelistria** [comment]
An issue is that the gson bundle isn't available as a p2 artifact and than cannot be referenced by a portable .target file.
We'll need to wait for ls-api to include the gson bundle, or for Orbit to get a newer version to have be able to make a good target definition.

**Comment by bruno-medeiros** [comment]
We could have the build script generate it, see #20.

**Comment by bruno-medeiros** [comment]
Whilst on the topic of IDE configuration, I also get a few of `Plugin execution not covered by lifecycle configuration: org.eclipse.tycho:tycho-packaging-plugin:0.25.0:` errors. I never used M2E before, so I'm not sure what these mean exactly, nor what's the best way to deal with them.

**Comment by mickaelistria** [comment]
There should be a m2e-tycho connector. m2e should prompt its installation by default or as a quick-fix for this error message, or you can install it via `Preferences > Maven > Discovery > Open Catalog`.

**Comment by mickaelistria** [comment]
I've added a TP based on your proposal and the various discussion we've had https://github.com/eclipselabs/eclipse-language-service/commit/ba12025fcca2b94642b1d1f3795b024147cc6935
Is it good enough for you? Should we close this issue?

**Comment by bruno-medeiros** [comment]
Yeah, good enough

**Comment by mickaelistria** [comment]
Thanks..
