### ISSUE TITLE
add support for refactorings

### ISSUE THREAD

**Issue by mickaelistria** [eclipselabs/eclipse-language-service#10]
Add support for refactorings coming from a language server into IDE Refactoring menu.

**Comment by mickaelistria** [comment]
Refactorings are not yet part of Language Server Protocol: https://github.com/Microsoft/language-server-protocol/issues/61

**Comment by mickaelistria** [comment]
@gorkem: did you expose some refactorings via JDT language server? If yes, which operation in the protocol did you bound them to?

**Comment by gorkem** [comment]
No, we have not. JDT Server also has the issue that most of the refactoring implementations are on the UI packages.

**Comment by mickaelistria** [comment]
Closed. As this is much an upstream bug, I don't think it's worth moving it to bugzilla right now.
