### ISSUE TITLE
Move to Eclipse.org

### ISSUE THREAD

**Issue by mickaelistria** [eclipselabs/eclipse-language-service#102]
The project is going to move to Eclipse.org as LSP4E.
Code and issues will be moved soon.

**Comment by mniewrzal** [comment]
Btw, It will stay on github?

**Comment by mickaelistria** [comment]
Nope, it will move to Gerrit@Eclipse.org.

**Comment by mickaelistria** [comment]
CQ has been approved. Code should be checked in soon (tomorrow) @Eclipse.org.

**Comment by mickaelistria** [comment]
Waiting on https://bugs.eclipse.org/bugs/show_bug.cgi?id=508326

**Comment by mniewrzal** [comment]
Github issues will be moved automatically?

**Comment by mickaelistria** [comment]
I don't know yet, I'll ask once source code is moved.
If not, I'll take care of re-creating bugzillas manually.

**Comment by mniewrzal** [comment]
> If not, I'll take care of re-creating bugzillas manually.

I can help with that if it will be necessary.

**Comment by mickaelistria** [comment]
The Eclipse.org migration policy required to drop the history. But source code is now at http://git.eclipse.org/c/lsp4e/lsp4e.git . Gerrit is enabled. Happy contributing!

**Comment by mickaelistria** [comment]
The only remaining thing for a complete migration is now migration of issues. I've asked about it and will report feedback.

**Comment by mickaelistria** [comment]
Done. moving from GitHub to Eclipse.org reminds me changing job from a startup to an established company ;)

**Comment by bruno-medeiros** [comment]
Hum, how can I configure Bugzilla to automatically subscribe me to all new LSP4E issues?

**Comment by mickaelistria** [comment]
Hey Bruno, would you mind asking that on the lsp4e-dev@eclipse.org mailing-list?
