### ISSUE TITLE
cursor positioning is broken

### ISSUE THREAD

**Issue by martinlippert** [eclipselabs/eclipse-language-service#104]
after doing code completion, the cursor positioning is somewhat broken, I think.

I have a file (called manifest.yml):
```
appl<cursor>
```
then I do code completion, which returns "applications:\n- " as the new text. That looks good. But after the code completion happened, I get this:
```
appl<cursor>ications:
- 
```
which is the correct text content, but the cursor positioning is funny and renders this code completion somewhat useless.

VS Code turns this code completion into:
```
applications:
- <cursor>
```
which is great. I think the Eclipse integration should do the same.

**Comment by mniewrzal** [comment]
I'm working with cursor position improvements at the moment. Which language server do you use?

**Comment by martinlippert** [comment]
Our own, something we are working on at the moment...

**Comment by mickaelistria** [comment]
Change merged in LSP4E: https://git.eclipse.org/r/#/c/86025/ , thanks
