### ISSUE TITLE
Support for file system (file outside Workspace)

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#109]
It's perhaps an issue with GenericEditor but when I open a JSON, CSS file which doesn't belong to the Workspace (drap-drop a file in the Eclipse IDE), the GenericEditor seems not be used:

 * I have none errors (my file has JSON which not valid)
 * the editor is not colorized with my TextMate grammar.

**Comment by mickaelistria** [comment]
The Language Server integration is at the moment tied to the Eclipse resource/project model, then it's not (yet) working for any given file.

The issue with the file not being open with the Generic Editor would be Platform one. However, before I ask you to report it to Platform, can you please verify the the Generic Editor is the default editor in your workspace even for workspace files?

**Comment by mickaelistria** [comment]
Replaced with https://bugs.eclipse.org/bugs/show_bug.cgi?id=508488
