### ISSUE TITLE
read result of initialize to decide of features activation

### ISSUE THREAD

**Issue by mickaelistria** [eclipselabs/eclipse-language-service#17]
The current implementation assumes all operations are availablw and request them to LS anyway. We should rather check the result of the initialization to decide whether to make feature enabled in Eclipse and whether to perform the request.

**Comment by mickaelistria** [comment]
Goal is to have something like `LanguageServerAccessor.getLanguageServer(file, InitializeResult::isHoverProvider)` would be good.

**Comment by vladdu** [comment]
Another way would be to expose something like IHoverService, defining only the relevant LS methods, and enable it using the initialization result. 

Some features might require disabling stuff in plugin.xml... I don't have any good suggestion about that, at the moment.

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipselabs/eclipse-language-service/commit/9109e124e5093472ff573a8772b4b34c1f00711b
