### ISSUE TITLE
Use NLS

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#24]
You should use NLS instead of using String. I suppose that it was not your priority when you have started the project, but IMHO if you do not that now, you will do never (I know it's a boring job).

**Comment by mickaelistria** [comment]
Thanks for reminding. If you're interested in contributing this before it becomes high enough priority for me, that'd be highly welcome!

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipselabs/eclipse-language-service/commit/5216a1937cf7435c3f16da7779cd3a9fb1c5994f

**Comment by angelozerr** [comment]
Thanks @mickaelistria! Sorry for this borring job.
