### ISSUE TITLE
Provide a Language Server launch (instead of Program launch)

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#25]
Today you are using Program launch, but I find it's not a clean mean. I think you should provide a new "Language Server launch"  which call the "Program" launch (without saving it).

A "Language Server launch"  will give you several benefit like provide a custom UI preferences:
- the node path (or an embed nodejs)
- a text with Browse button to select the JSON, CSS etc server.

The JSDT project follows this idea for npm, grunt, etc. It uses https://git.eclipse.org/c/jsdt/webtools.jsdt.git/tree/nodejs/org.eclipse.wst.jsdt.js.cli/src/org/eclipse/wst/jsdt/js/cli/core/CLI.java

**Comment by mickaelistria** [comment]
Although at the moment, all language servers I've seen are using Node, it is not a requirement and we have to keep implementation independent from node.js.
However, for the current examples, it would indeed be interesting to reuse JSDT Node launch config directly rather than a Program Launch.

**Comment by guw** [comment]
@mickaelistria Any thoughts on usability? Launch configs are truly nice from a dev perspective. However, presenting that to some other people I got feedback that they are confusing and it's a technical detail that should better be hidden.

**Comment by kaloyan-raev** [comment]
@mickaelistria This one is implemented in pure PHP: https://github.com/felixfbecker/php-language-server

**Comment by mickaelistria** [comment]
@guw: AFAIK, if we want to run external programs properly in Eclipse IDE, there isn't much alternative, is there? Moreover, on the long run, I expect the Language Server Launch Configuration to be created by plugins in a smart way (finding right path or coming with a configuration wizard), without requiring users to know about and manipulate Launch Configurations.

**Comment by guw** [comment]
They should be just processes in the background. There is no need for launch configs IMO. Ideally, users won't even realize something has been started in the background.

**Comment by mickaelistria** [comment]
The benefit with Launch Configurations is that they allow environment specific tweaks. For example, OmniSharp require to override the LD_LIBRARY_PATH on most Linux distributions. The Launch Configuration gives this ability to user for free.
However, on the long run, if language server all work smoothly without any need for tweak, independent processes would be simpler. But it would require to setup yet-another registry to store the known language servers, whereas we currently reuse the Launch Configuration registry.
So I think you're right, but I have the impression it's too early to drop the Launch Configuration and its ability to let users customize how language servers are run.

**Comment by mickaelistria** [comment]
Some new advantages of relying on Run Configurations:
- Those can be shared as .launch file so a server configuration can be distributed and configured without installing a plugin
- If we allow Run Configuration, we can most likely also allow Debug Configuration and support issue #39 to allow development of Language Servers inside Eclipse with an immediate feedback loop.

**Comment by mickaelistria** [comment]
At the moment, there are no issues with allowing any Launch Configuration. It has allowed to fix #39, it allows users to manually add and configure new servers without installing anything. So let's close this one until an actual issue is found with this approach.
