### ISSUE TITLE
Provide an embed nodejs

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#26]
Today if you have not nodejs installed you cannot consume JSON, CSS VSCode language server. I remember that I had the same problem with tern.java and @maxandersen suggested me to provide an embed nodejs in order to avoid installing nodejs. The use of nodejs must be transparent for the final user.

I think more and more that nodejs support should be provided by Eclipse IDE:
- an UI preferences to customize the installed nodejs path
- an UI preferences to select an embed nodejs

This preferences could be used after by any plugin like tern.java, typescript.java, etc

If you are interesed, I could try to do a PR.

**Comment by mickaelistria** [comment]
What would be the value for end-users? Note that since this code is going to eclipse.org soon, it needs to remain IP-clean.

**Comment by angelozerr** [comment]
> What would be the value for end-users?

not to install nodejs

**Comment by mickaelistria** [comment]
Similar to #25 and #26. This repository is not the right place to store language specific work, it's better if it remains "pure" Eclipse, and then server integration providers are free to ship or configure whatever they want.
