### ISSUE TITLE
Provide an embed JSON server, CSS server, etc

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#27]
Provide an embed JSON server, CSS server, etc in order to avoid to the user to install VSCode, JSON, etc

**Comment by mickaelistria** [comment]
+1. That's currently a subject I'm delaying to after migration to eclispe.org as it involves a lot of IP work.

**Comment by kaloyan-raev** [comment]
FYI, according to [this comment](https://github.com/eclipse/che/issues/1287#issuecomment-248372479), the Che project plans to have a public registry for language servers.

I don't know any details, but I can imagine this registry can be hosted at Eclipse Foundation and the necessary IP work can be done centrally.

Note, that the current solution for Che is a public repository hosted at codenvy.com (see the same issue for details). Perhaps, the eclipse-language-service can reuse it as a temporary solution.

**Comment by mickaelistria** [comment]
The idea of fetching language servers from a remote registry rather than requesting users to manually install them is really good. A marketplace of language-servers is definitely something to consider!

**Comment by mickaelistria** [comment]
I opened https://github.com/Microsoft/language-server-protocol/issues/76

**Comment by mickaelistria** [comment]
This is more or less a dup of #26. I'm closing it for similar reasons, and similar comments about shipping an alternative bundle to `org.eclipse.languageserver.languages` apply.
