### ISSUE TITLE
Reorganize plugins

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#29]
org.eclipse.languageserver should be spliited into several plugins:
- org.eclipse.languageserver.core
- org.eclipse.languageserver.ui
- org.eclipse.languageserver.csharp.core
- org.eclipse.languageserver.csharp.ui
- org.eclipse.languageserver.json.core
- org.eclipse.languageserver.json.ui
- org.eclipse.languageserver.css.core
- org.eclipse.languageserver.css.ui

**Comment by mickaelistria** [comment]
Can you please elaborate about what would be the content of each of these bundles? I'm unsure splitting core and ui is meaningful there, as this integration has for sole goal to integrate language server in UI.

**Comment by mickaelistria** [comment]
Commit https://github.com/eclipselabs/eclipse-language-service/commit/2c58077d95288e7dcd8b7b60bd4d33597d485ca2 does extract the language-specific parts to a separated plugin. So everything inside the `org.eclipse.languageserver` bundle is totally independent from actual instances of language servers.

**Comment by angelozerr** [comment]
Thanks @mickaelistria !

Once the launch topic will be clear, we will able to to split org.eclipse.languageserver.languages into:
- org.eclipse.languageserver.languages.csharp
- org.eclipse.languageserver.languages.json
- org.eclipse.languageserver.languages.css

and find a solution to contribute to launch. This split will help the dev of another language (I'm experimenting for TypeScript).

**Comment by mickaelistria** [comment]
Does typescript server implement the language server protocol?

**Comment by angelozerr** [comment]
No, I'm trying to study it. If it's not complex I will implement it.

**Comment by mickaelistria** [comment]
Get in touch with the Typescript and VSCode people first. I know they plan to ship one together with the regular typescript tools. I can't tell about progress, status nor ETA.
Implementing a language server is going to take some time, and if TypeScript release an official one, yours will be entirely eclipsed by the official one. I'm not sure it's a bankable way to spend resources right now.

**Comment by mickaelistria** [comment]
I've opened https://github.com/Microsoft/TypeScript/issues/11274

**Comment by mickaelistria** [comment]
Closing as this is not really an issue at the moment. We'll probably have to reconsider how the "languages" bundle is organized as LSP4E or downstream project start shipping actual support for languages with existing language servers.
