### ISSUE TITLE
Initialize nodejs path used in the launch according the OS

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#32]
Today, nodejs path is hard coded. It should be better to initialize nodejs path according teh OS
- try to find nodejs path in the known directory according the OS (ex :`C:/Program Files/nodejs/node.exe` for Windows, `/usr/local/bin/node` for linux)
- if not found, try to retrieve node inside PATH env.

In other words:
- create a `org.eclipse.languageserver.util.NodejsHelper` class
- provide a `NodejsHelper#getNodejsPath()` which retrieve node path.

I have already done that for tern.java and typescript.java. If you are interesed, I could do a PR.

**Comment by mickaelistria** [comment]
I had in mind, once the support for CSS, JS and C# are in a separate bundle, to consume the JSDT node.js integrations and runners for those. What do you think about it?

**Comment by angelozerr** [comment]
the JSDT node.js integrations doesn't support this feature if I remember. NodejsHelper is a very basic class. You could remove to JSDT node.js integration after.

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipselabs/eclipse-language-service/commit/c5ef849e3502e8c090c31012e9e6bd0a99331c49 and https://github.com/eclipselabs/eclipse-language-service/commit/2e8fb0fd8b01d1f3858707e97edffe9b0b0460fb
