### ISSUE TITLE
Connection with LS happens late after editor is opened

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#41]
Take a simple sample:
- create a not valid **test.json** (outside Eclipse) with this content:

`{`
- copy/paste **test.json** in your Eclipse workspace.

Open test.json, the errors doesn't appear.

**Comment by mickaelistria** [comment]
At the moment, the validation is triggered when editor is connected to the language server. That does happen lazily if user requests a LS feature such as completion.
Instead, the connection of the editor/resource with language server should happen whenever the resource is open by an editor.

**Comment by svenefftinge** [comment]
I think the 'connection' should happen even before that, because a language server watches a certain path and sends notifications also for resources that are not opened in editors.

**Comment by mickaelistria** [comment]
Moved to https://bugs.eclipse.org/bugs/show_bug.cgi?id=508460
