### ISSUE TITLE
Remove dependency to WTP (for content type)

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#42]
If you have not Eclipse WTP which defines content types `org.eclipse.wst.jsdt.core.jsonSource` and `org.eclipse.wst.css.core.csssource`, the JSON/CSS Editor with Generic Editor doesn't work because thoses content type are not defined.

Perhaps a solution is to define again `org.eclipse.wst.jsdt.core.jsonSource`

```
<content-type
        base-type="org.eclipse.core.runtime.text"
        file-extensions="json"
        id="org.eclipse.wst.jsdt.core.jsonSource"
        name="JSON"
        priority="normal">            
  </content-type>
```

Or working with a new content type `org.eclipse.languageserver.languages.json` which extends `org.eclipse.wst.jsdt.core.jsonSource`

```
<content-type
        base-type="org.eclipse.wst.jsdt.core.jsonSource"
        file-extensions="json"
        id="org.eclipse.languageserver.languages.json"
        name="JSON"
        priority="normal">            
  </content-type>
```

I don't what is the better clean mean. I post just some ideas without testing.

**Comment by mickaelistria** [comment]
Redefining the same content-type isn't recommended as `id` are supposed to be really unique. Having another content-type seems cleaner.

**Comment by angelozerr** [comment]
I agree with you.

**Comment by angelozerr** [comment]
I think we should:
- define a new org.eclipse.languageserver.languages.json
- support both org.eclipse.languageserver.languages.json and org.eclipse.wst.jsdt.core.jsonSource for completion, hover, etc

**Comment by mickaelistria** [comment]
No need to define support for both, see https://github.com/eclipselabs/eclipse-language-service/blob/master/org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java#L172 . The Language Server Eclipse integration will attach the language server for any content-type that matches this file.
So if we have an org.eclipse.languageserver.languages.json associated to .json files and have the language server associated to this content-type, then all .json file can receive extensions from language server, with or without org.eclipse.wdt.jsdt.core.jsonSource available.

**Comment by angelozerr** [comment]
Buf if we have WTP, the JSON file will have org.eclipse.wst.jsdt.core.jsonSource  content type and not org.eclipse.languageserver.languages.json, no?

**Comment by mickaelistria** [comment]
A file can have several content-types and can simultaneously be `org.eclipse.wst.jsdt.core.jsonSource` and `org.eclipse.languageserver.languages.json`. The LanguageServerAccessor is supposed to find association for any of those. If it doesn't, then it's a bug.

**Comment by angelozerr** [comment]
> A file can have several content-types 

Thank's for this info! I dodn't know that.

**Comment by mickaelistria** [comment]
Should be fixed with https://github.com/eclipselabs/eclipse-language-service/commit/5f640408ca34a47f6f3efeb5950a197024bd1705

**Comment by angelozerr** [comment]
Thanks @mickaelistria !
