### ISSUE TITLE
Don't save dirty editors when VSCode-JSON, VSCode-CSS etc launch start

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#43]
When the `VSCode-JSON`launch is started it saved dirty editors. It can be strange if you are editing a txt file for instance and you open a JSON file and you open completion.

This behaviour is because of https://github.com/eclipse/eclipse.platform.debug/blob/master/org.eclipse.debug.core/core/org/eclipse/debug/core/model/LaunchConfigurationDelegate.java#L255

You can disable this behaviour with `Save required dirty editors before launching` from `Preferences > Run/Debug > Launching`, but I think it's shame.

I don't know how to disable `Save required dirty editors before launching`  for a specific launch (i sit possible?) Perhaps a solution is to define a LSConfigurationDelegate which extends saveBeforeLaunch to avoid saving dirty editors.

**Comment by mickaelistria** [comment]
Yeah, I tried several options to avoid need to save editors but didn't find anything successful so far. Any help on this is welcome!

**Comment by angelozerr** [comment]
I think a custom launch will fix this problem.

**Comment by mickaelistria** [comment]
Replaced with https://bugs.eclipse.org/bugs/show_bug.cgi?id=508461
