### ISSUE TITLE
Syntax Coloring for JSON

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#45]
Like charp, it should be very nice to have syntax coloring for JSON.

If you wish I could try to do a PR.

**Comment by mickaelistria** [comment]
You could reuse the PresentationReconcilier from WTP for that, however, you'll face this current bug (that should be fixed soon) https://bugs.eclipse.org/bugs/show_bug.cgi?id=500755

**Comment by mickaelistria** [comment]
But simpler reconcilier would be welcome too, as PRs. However, I'm not sure they'll end in the Eclipse.org repository when this project moves, as I think they'd make more sense in WTP.

**Comment by mickaelistria** [comment]
@angelozerr do you have plans or deadlines about the CSS syntax highlighting?

**Comment by angelozerr** [comment]
@mickaelistria I'm very busy for the moment with release of typescript.java 1.1.0. As soon as I will finish this release, I will try to see it, but I cannot promise you -(

**Comment by mickaelistria** [comment]
@angelozerr I'm closing this as I believe this issue is more for your Textmate-Eclipse integration. Note that I think both integrations should remain independent, but be able to work together on the same generic editor. As far as I understood, that's already the case.
