### ISSUE TITLE
Syntax Coloring for CSS

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#46]
Like charp, it should be very nice to have syntax coloring for CSS.

If you wish I could try to do a PR.

**Comment by mickaelistria** [comment]
A simple PR would be welcome.
Just so you know, when this project moves to Eclipse.org, I'm not sure yet whether language-specific examples will follow. Maybe they'll stay here, maybe they'll move to the Eclipse.org project, maybe they'll move to some other Eclipse project...

**Comment by mickaelistria** [comment]
@angelozerr I'm closing this as I believe this issue is more for your Textmate-Eclipse integration. Note that I think both integrations should remain independent, but be able to work together on the same generic editor. As far as I understood, that's already the case.

**Comment by angelozerr** [comment]
Yes sure, thanks @mickaelistria
