### ISSUE TITLE
[Completion] Support for triggers chars

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#48]
Use ServerCapabilities#getCompletionProvider#getCompletionOptions#getTriggerCharacters to initialize completion processor to support triggers chars.

**Comment by mickaelistria** [comment]
+1. However it may also require some code to adopt triggerChars this in the Generic Editor as well.

**Comment by mickaelistria** [comment]
This depends on https://bugs.eclipse.org/bugs/show_bug.cgi?id=505632

**Comment by mickaelistria** [comment]
And a good integration also requires https://bugs.eclipse.org/bugs/show_bug.cgi?id=505635

**Comment by mickaelistria** [comment]
@angelozerr I pushed a change that should support it. However, I didn't manage to find a working language server that uses it. Do you have an example to suggest? If not, I'll probably just close this issue.

**Comment by kaloyan-raev** [comment]
@mickaelistria Try the JSON language server: https://github.com/Microsoft/vscode/blob/c67ef57cda90b5f28499646f7cc94e8dcc5b0586/extensions/json/server/src/jsonServerMain.ts#L64

**Comment by mickaelistria** [comment]
I'd like to, but there's https://github.com/TypeFox/ls-api/issues/63 blocking good integration of JSON server.

**Comment by mniewrzal** [comment]
Autoactivation works ok but only after first manual activation (ctrl+space). Before that LSPDocumentInfo isn't computed for LSContentAssistProcessor.

**Comment by mickaelistria** [comment]
Moved to https://bugs.eclipse.org/bugs/show_bug.cgi?id=508463
