### ISSUE TITLE
[Completion] Highlight completion items according current word (like Recommanders)

### ISSUE THREAD

**Issue by angelozerr** [eclipselabs/eclipse-language-service#50]
It should be very good to highlight completion items according current word (like Recommanders). I have already done that for typescript.java

![](https://github.com/angelozerr/typescript.java/wiki/images/TypeScriptCompletionDemo.gif)

If you are interested, I could do a PR.

**Comment by mickaelistria** [comment]
Yes, such feature would be welcome. However, it needs to be considered carefully which parts should go to the Generic Editor directly, and which parts should remain on the language server integration here.

**Comment by mickaelistria** [comment]
Also, note that subword completion and highlighting is now directly in JDT (no need for recommenders to have this).

**Comment by angelozerr** [comment]
To support this issue we need to retrieve the word according the language. Today it's not possible. See https://github.com/eclipselabs/eclipse-language-service/issues/49#issuecomment-251617462

**Comment by mickaelistria** [comment]
Replaced with https://bugs.eclipse.org/bugs/show_bug.cgi?id=508467
