### ISSUE TITLE
Tycho builds fails due to "org.eclipse.ui.genericeditor" dep missing

### ISSUE THREAD

**Issue by bruno-medeiros** [eclipselabs/eclipse-language-service#6]

**Comment by mickaelistria** [comment]
@scela do you think https://git.eclipse.org/r/#/c/75921/ could include a p2 repo with the generic editor parts, and that we could publish somewhere (as a locked build on Jenkins maybe?) So it could be refenced from this build?

**Comment by mickaelistria** [comment]
As the LSP support bundle only uses extensions from org.eclipse.ui.genericeditor and no class, the dependency could be marked as optional.

**Comment by mickaelistria** [comment]
I added a submodule to reference that dependency (referencing the Gerrit patch). However cloning the Gerrit repository doesn't automatically fetch the necessary reference to resolve the right commit. See https://travis-ci.org/eclipselabs/eclipse-language-service

@bruno-medeiros Do you know whether it's possible to customize the step responsible for updating submodules with travis? Or maybe if there are some magic to get Git submodules to find the right commit/reference from Gerrit?

**Comment by mickaelistria** [comment]
I also asked http://stackoverflow.com/questions/20109215/git-submodule-track-commit-but-know-branch on this topic.

**Comment by bruno-medeiros** [comment]
I don't know anything about git submodules I'm afraid.

**Comment by mickaelistria** [comment]
Change in PR #13 fix this. It uses a declared branch containing the generic editor proposal from a GitHub clone so submodule can see it.

**Comment by bruno-medeiros** [comment]
So, what git command to I have to run to download the submodule?

BTW, I'm still confused as to what "org.eclipse.ui.genericeditor" is exactly. Shouldn't this just be part of the eclipse-language-service repo?

**Comment by mickaelistria** [comment]
> So, what git command to I have to run to download the submodule?

I believe `git submodule update --init --recursive`.

> BTW, I'm still confused as to what "org.eclipse.ui.genericeditor" is exactly. Shouldn't this just be part of the eclipse-language-service repo?

See https://git.eclipse.org/r/#/c/75921/ . @scela and I already have used in it many contexts: Language Server integration, quick textual editor for .target, .project, build.gradle, reusing coloring from LiclipseText... all that with a single editor and way less effort than traditional subclassing.
Simplifying support for new languages (by relying on an extensible editor) is one of the Platform UI themes for the Oxygen release, this is the main piece.

**Comment by bruno-medeiros** [comment]
> I believe git submodule update --init --recursive.

Ok, that worked. It should be documented somewhere though.

> ```
> BTW, I'm still confused as to what "org.eclipse.ui.genericeditor" is exactly. Shouldn't this just be part of the eclipse-language-service repo?
> ```
> 
> See https://git.eclipse.org/r/#/c/75921/ . @scela and I already have used in it many contexts: Language Server integration, quick textual editor for .target, .project, build.gradle, reusing coloring from LiclipseText... all that with a single editor and way less effort than traditional subclassing.
> Simplifying support for new languages (by relying on an extensible editor) is one of the Platform UI themes for the Oxygen release, this is the main piece.

Ok, that makes sense, but then why is not part of eclipse-language-service repo? Or do you have changes to Platform UI code there?

**Comment by mickaelistria** [comment]
> Ok, that worked. It should be documented somewhere though.

Feel free to start a contribution guide on the Wiki page of the repo. I'm about to open permissions.

> Or do you have changes to Platform UI code there?

Yes, the piece of code is actually this Gerrit patch for platform UI: https://git.eclipse.org/r/#/c/75921 . I didn't find a way to directly reference Gerrit, that's why it's referencing my fork, but it's Platform-UI code. See also http://stackoverflow.com/questions/39129164/a-git-submodule-to-a-non-declared-reference-from-gerrit

**Comment by bruno-medeiros** [comment]
> Feel free to start a contribution guide on the Wiki page of the repo. I'm about to open permissions.

I'd rather this would be documented in README.md, or elsewhere in the Git repo. This way, changes to the build script or git submodules config can be made in sync with the documentation changes. That is, the config change and documentation change (which are intrinsicaly linked) can be made in the same commit.

> ```
> Or do you have changes to Platform UI code there?
> ```
> 
> Yes, the piece of code is actually this Gerrit patch for platform UI: https://git.eclipse.org/r/#/c/75921 . I didn't find a way to directly reference Gerrit, that's why it's referencing my fork, but it's Platform-UI code. See also http://stackoverflow.com/questions/39129164/a-git-submodule-to-a-non-declared-reference-from-gerrit

Oh I get it now. GenericEditor is the eclipse extension, and is not tied to LSP per se, it's only eclipse-language-service that is tied to LSP.

**Comment by mickaelistria** [comment]
> I'd rather this would be documented in README.md

The readme.md has to remain more like a feature presentation, I prefer avoiding too much details about how to contribute in it.

> or elsewhere in the Git repo. This way, changes to the build script or git submodules config can be made in sync with the documentation changes. That is, the config change and documentation change (which are intrinsicaly linked) can be made in the same commit.

Right. There's an `adoc` folder which already contains a page. You can create a contribution guide here and link to it from README.md. Is it ok if we proceed by pull requests or do you prefer commit permissions directly?

**Comment by bruno-medeiros** [comment]
> I'd rather this would be documented in README.md
> 
> The readme.md has to remain more like a feature presentation, I prefer avoiding too much details about how to contribute in it.

Yes, the target platform config and doc other info is essentially the "Contributer's Guide", which is fine to be a different document.

> ```
> or elsewhere in the Git repo. This way, changes to the build script or git submodules config can be made in sync with the documentation changes. That is, the config change and documentation change (which are intrinsicaly linked) can be made in the same commit.
> ```
> 
> Right. There's an adoc folder which already contains a page. You can create a contribution guide here and link to it from README.md. Is it ok if we proceed by pull requests or do you prefer commit permissions directly?

I'm ok with PRs for now.
