### ISSUE TITLE
Consider the debug server protocol

### ISSUE THREAD

**Issue by mickaelistria** [eclipselabs/eclipse-language-service#60]
See https://github.com/Microsoft/vscode-debugadapter-node and https://github.com/Microsoft/vscode-debugadapter-node/wiki/VS-Code-Debug-Protocol-Implementations

**Comment by mickaelistria** [comment]
@gorkem Are you aware of something that would generate a Java client easily with JSON-RPC protocol according to a json schema? The debug protocol has a schema.

**Comment by gorkem** [comment]
JDT LS has a [json schema](https://github.com/gorkem/java-language-server/blob/master/lang-protocol-generator/ls-protocol/everything.json) for LSP and [generates](https://github.com/gorkem/java-language-server/blob/master/lang-protocol-generator/pom.xml) the Java model from it. That should also work for debug protocol.

**Comment by mickaelistria** [comment]
On the long run, the debug protocol would rather be a separate project. However, let's keep the issue open until something starts to happen regarding consuming debug protocol in Eclipse IDE.

**Comment by mickaelistria** [comment]
Replaced with https://bugs.eclipse.org/bugs/show_bug.cgi?id=508470
