### ISSUE TITLE
Chain of TextEdits must be applied in reverse order (from max offset to min one)

### ISSUE THREAD

**Issue by mickaelistria** [eclipselabs/eclipse-language-service#65]
See https://github.com/Microsoft/language-server-protocol/commit/e1e59508d52e7451ed8cf94bee99e5b5cbdfd99c
cc @mniewrzal

**Comment by mniewrzal** [comment]
It looks that org.eclipse.text.edits.TextEdit infrastructure is handling this. I was applying text edits as separate edits and then the process was crashed by invalid offsets but when MultiTextEdit is used its not a problem anymore.

**Comment by mickaelistria** [comment]
Ok, great. Let's close it then.
