### ISSUE TITLE
LS initialization is done with every context menu display

### ISSUE THREAD

**Issue by mniewrzal** [eclipselabs/eclipse-language-service#66]
Like in title.

**Comment by mickaelistria** [comment]
I cannot reproduce it with the VSCode-JSON language server. LS initialization can typically happen if connection was lost (stream closed or LSP4J reporting an error). An issue on server-side or a bad message can trigger a re-initialization.

**Comment by mniewrzal** [comment]
Ok, thanks. Maybe something is wrong on my side. I will double check this.

**Comment by mniewrzal** [comment]
I cleaned/updated all sides of my configuration and everything is ok now. Looks that problem was on my side. Closing.

**Comment by mniewrzal** [comment]
I tracked this issue. When `ProjectSpecificLanguageServerWrapper` was initialized but server is not supporting given `ServerCapabilities` then new instance of `ProjectSpecificLanguageServerWrapper` will be created and initialization will be done once again. 

In my case I'm playing with php LS where refactoring isn't supported and because of that each `LanguageServiceAccessor.getLSPDocumentInfoFor(textEditor, (capabilities) -> Boolean.TRUE.equals(capabilities.isRenameProvider()))` (handler for rename) will reinitialize LS.

**Comment by mickaelistria** [comment]
Fixed with 7e1767d763dd06e8a8884840be4ce342a7c9b736 , thanks @mniewrzal for doing a huge part of the investigation (and sorry for forgetting to credit in the commit message...)
