### ISSUE TITLE
[Outline/Symbols] misses "Link With Editor"

### ISSUE THREAD

**Issue by mickaelistria** [eclipselabs/eclipse-language-service#70]
The LSP-based outline misses the "Link with editor" feature.

**Comment by mniewrzal** [comment]
Also double click should work for outline elements.

**Comment by mickaelistria** [comment]
What do you expect from double-click: expand of go to element in editor?

**Comment by mniewrzal** [comment]
> What do you expect from double-click: expand of go to element in editor?

I was thinking about go to element in editor. This is default behavior for JDT and other outlines. I think this project should be consistent with main plugins. To be specific double click is showing element and selecting it.

**Comment by mickaelistria** [comment]
Yeah. I'm currently trying to reuse/mimic things from Project Explorer for consistency sake.

**Comment by mniewrzal** [comment]
Most projects overrides default 'expand' on double click behavior ;)

**Comment by mickaelistria** [comment]
I think expand is the default in Project Explorer, unless a linkHelper works for the selected node.

**Comment by mniewrzal** [comment]
From my experience link helper should only shows elements in opened editors. As an example you can take a look at `org.eclipse.ui.internal.navigator.resources.workbench.ResourceLinkHelper`. To provide double click for model elements plugins overrides `org.eclipse.ui.navigator.resources.OpenActions` action provider.

**Comment by mickaelistria** [comment]
This issue is actually quite tricky as the CNF APIs don't seem to expose the LinkHelpersService to customers and because there is no good class to use/subclass that provides it. It most likely needs some additions to CNF APIs.

**Comment by mickaelistria** [comment]
Replaced with https://bugs.eclipse.org/bugs/show_bug.cgi?id=508472
