### ISSUE TITLE
Move symbol problems decoration to separate decorator 

### ISSUE THREAD

**Issue by mniewrzal** [eclipselabs/eclipse-language-service#82]
Maybe it would be more optimal to have separate ILightweightLabelDecorator for problems decoration?

**Comment by mickaelistria** [comment]
Yeah probably. However, at the moment, I didn't observe a visible performance penalty with current implementation.
So I don't plan to fix it very soon, as I put priority on other issues; but any better alternative would be very welcome!

**Comment by mniewrzal** [comment]
I added this issue as nice to have :) nothing very important at the moment. Its more about simpler/cleaner code.

**Comment by mickaelistria** [comment]
Replaced by https://bugs.eclipse.org/bugs/show_bug.cgi?id=508481
