### ISSUE TITLE
Move to LSP4J

### ISSUE THREAD

**Issue by svenefftinge** [eclipselabs/eclipse-language-service#85]
LSP4J is ready to be used. As part of the transition we overworked the code (and reimplemented in in Java), so that might involve some changes on your side.
I've written down some pointers to start with https://github.com/eclipse/lsp4j/tree/master/documentation

Please let me know if you need help (just file issues over at lsp4j).

**Comment by mickaelistria** [comment]
Current blocker in LSP4J: https://github.com/eclipse/lsp4j/issues/5

**Comment by mickaelistria** [comment]
WIP at https://github.com/mickaelistria/eclipse-language-service/tree/issue-85

**Comment by mickaelistria** [comment]
Spotted a regression in LSP4J: https://github.com/eclipse/lsp4j/issues/7

**Comment by mickaelistria** [comment]
Despite the spotted regression, I'm about to merge #90  right now, as usage of LSP4J is very high priority work, that it's refactoring that will make merging later harder, and we can expect LSP4J to be fixed soon.

**Comment by mickaelistria** [comment]
Fixed with acf2091
