### ISSUE TITLE
how to debug the editor and the language server simultaneously

### ISSUE THREAD

**Issue by martinlippert** [eclipselabs/eclipse-language-service#86]
Do you have any best practices how to to debug the language server integration for Eclipse as well as the language server itself?

I have a runtime workbench running the generic editor with the language server integration and can debug that just fine (start in debug mode). Now I am looking for a way to debug the language server itself as well (which is a Java app in my case). I can configure the launch config of the language server in my runtime workbench with debug options and then connect a remote debugging session to it (from my host environment), but I am looking for a more “natural” way (e.g. start the language server in debug mode from my host environment, start my runtime workbench, let the editor in the runtime workbench connect to the already running language server). Is there a way to do that? Or is there an even better way to do debug both (editor and language server) simultaneously?

**Comment by mickaelistria** [comment]
First, I believe using a Remote Debugger isn't a bad approach. Actually, despite requiring more steps, it might be one of the more "natural" ones as it doesn't require a different design to debug stuff.

If the "Run Configuration" type you're using supports the "Debug" mode, then you can set up an association with a Debug Configuration to start the Language Server in Debug Mode by default through the `Preferences > Language Servers > New...` dialog. But it's deadlock-prone and it doesn't seem to cover that much your use-case at first sight.

In your case, if everything is Java, you could also imagine creating a Launch Configuration which wouldn't start a new process and just act as a daemon thread. I believe that kind of use-cases wouldn't work out-of-the-box and would require some tweaks in the code of eclipse-language-service though. But those would be welcome contribution.
And same thing for the ability to connect to an already running server. I imagine you could setup a "proxy" Launch Configuration to access the streams of this server. It might be doable without change in the code.

@vladdu @mniewrzal @bruno-medeiros Maybe you've already found nicer ways to do that?

**Comment by vladdu** [comment]
My server is not in Java, so I don't have this problem. 

As an alternative to what Mickael suggested last, you could run/debug the server inside the same process as the client with some flag that skips using a launch configuration and just starts the thread. That's what I would do, because getting launch configs to do that might be tricky and I don't want to spend time wrestling with them.

**Comment by bruno-medeiros** [comment]
So far, I've only played around with https://github.com/RustDT/RustLSP/tree/master/subcrates/DummyLSP and LSP4J example code. The easiest way I found to debug my LS was to start it separately, and have the client connect to it with TCP, instead of the client spawning the process.

**Comment by mickaelistria** [comment]
Hi folks,
As we're moving to Bugzilla and Gerrit and so on, I'm close the issue.s I still have the impression this topic is worth discussing and can lead to concrete actions on how to improve LSP4E.
Feel free to continue discussion on the [official mailing-list](https://dev.eclipse.org/mailman/listinfo/lsp4e-dev).
