### ISSUE TITLE
Requesting not available operations kicks off another language server instance

### ISSUE THREAD

**Issue by martinlippert** [eclipselabs/eclipse-language-service#87]
in my case hovers are not yet implemented in the language server (and therefore returning nothing). When I hover over something, the editor saves the file (including the confirmation dialog, but that is another issue, I think) and kicks off another instance of the language server. So every hover request results in +1 instance of the language server.

**Comment by mniewrzal** [comment]
See #66. I'm preparing fix for that.

**Comment by mickaelistria** [comment]
@martinlippert Which build are you using?

**Comment by martinlippert** [comment]
I am running Eclipse Oxygen SDK M3 (I20161027-0700) + master of (generic editor) + master of (eclipse-language-server)

**Comment by mickaelistria** [comment]
Thanks, I could reproduce it with another operation and another language server. @mniewrzal is on the right track.

**Comment by mickaelistria** [comment]
@mniewrzal I've made another patch, inspired from yours, but trying to keep ability to associate a project with multiple LS.

**Comment by mickaelistria** [comment]
Fixed with 7e1767d763dd06e8a8884840be4ce342a7c9b736
