### ISSUE TITLE
Formatting for JSON stops working

### ISSUE THREAD

**Issue by mniewrzal** [eclipselabs/eclipse-language-service#93]
After recent changes context menu option 'Format' is disabled.

**Comment by mickaelistria** [comment]
Do you think this could be an issue in LSP4J ? If so, feel free to report it there, they're expecting us to help them finding issues and providing suggestions.
Did you manage to see the ServerCapabilities returned by the language server and whether they do declare the formatterProvider?

**Comment by mniewrzal** [comment]
> Did you manage to see the ServerCapabilities returned by the language server and whether they do declare the formatterProvider?

I didn't go into details yet, I plan to take a look at this tomorrow. For sure JSON formatting was working earlier :)

**Comment by mniewrzal** [comment]
Formatting stops working because my JSON LSP supports only range formatting. I don't know why this works earlier, maybe recent VSCode update changed this LSP implementation. I will prepare PR to use range formatting in case when standard formatting is not supported.

**Comment by mniewrzal** [comment]
Support range formatting #94

**Comment by mniewrzal** [comment]
Fixed by #94
