### ISSUE TITLE
Add extension point for LS definition

### ISSUE THREAD

**Issue by mniewrzal** [eclipselabs/eclipse-language-service#96]
I think that to support different language servers we need a easy and programmatic way to define it. Such extension should give ability to spawn LS and match it with content type. Maybe should also give a place to define LS configuration. 

Additional plugin per LS can be a place where content type can be defined and most probably syntax highlighting. Also actual implementation doesn't give an option to support more advanced case like TCP communication instead of stdin/stdout.

**Comment by svenefftinge** [comment]
Also do you have any plan for cases where I have extended the protocol itself with something, I want to enable on the client side? 
E.g. in this example [1] we have a special action, that sends an 'evaluate' request to the language server and displays it inline (CTRL + ENTER). Can you imagine how I would do that with Eclipse's LSP support?

[1] - http://52.29.251.2/calcmonaco/

**Comment by vladdu** [comment]
@svenefftinge This is an interesting issue. I will also want to use an extended protocol in the future.

Is it necessary to have support for this in the basic LS support? The simple way to handle this is to "just" implement the action and let the handler talk with the server. I'm not sure what advantages one would have by doing it with an extension point or similar, given that a handler is needed anyway to process the answer.

**Comment by mickaelistria** [comment]
@mniewrzal +1. Currently, all happens on preferences. See the examples in `org.eclipse.languageservice.languages` bundle that initiate language server (in a not very elegant way).

@svenefftinge  Please open a separate issue for that.

**Comment by svenefftinge** [comment]
Done #97

**Comment by martinlippert** [comment]
Any idea when this will be merged into master? I would love to use the extension point that got introduced in the commit mentioned above (in Michals fork)

**Comment by mickaelistria** [comment]
@martinlippert see https://github.com/eclipselabs/eclipse-language-service/pull/107#issuecomment-262508731

**Comment by martinlippert** [comment]
I see, understand... Any ETA? (wild guess maybe)

**Comment by mickaelistria** [comment]
Not really, it's more up to Eclipse IP team. A first iteration was already reviewed and I pushed an update containing legal "fixes" earlier today. I hope I'll hear again about it before the end of the week, then patches should be merged.

About extension points in general, I'd like to take advantage of the incubation status for some time before making them stable and API, so they could still evolve, even in a non-backward compatible way, for some time.
Such changes would be announceds on the [lsp4e-dev](https://dev.eclipse.org/mailman/listinfo/lsp4e-dev) mailing-list.

**Comment by martinlippert** [comment]
Sounds all good, thanks for the update. I will watch out on the lsp4e-dev list for further updates.

**Comment by mniewrzal** [comment]
@martinlippert btw, do you have any comments about extension point structure? Is it easy to use it for integration with your language server?

**Comment by martinlippert** [comment]
Yes, it looks nice to me. Will play with it in the next few days and let you know about my experiences.

**Comment by martinlippert** [comment]
I am playing with the extension point from the fork at the moment and it looks good to me. Great work.

**Comment by mickaelistria** [comment]
Change merged in LSP4E: https://git.eclipse.org/r/86026 . Thanks!

**Comment by martinlippert** [comment]
Great news!!! :-)
Is there already a continuous p2 repo being published anywhere?

**Comment by mickaelistria** [comment]
Yep, it's http://download.eclipse.org/lsp4e/snapshots/ (listed on https://projects.eclipse.org/projects/technology.lsp4e/downloads )

**Comment by martinlippert** [comment]
That is great, thanks!!! Contributions from now on via Gerrit, I guess?

**Comment by mickaelistria** [comment]
Yes
