### ISSUE TITLE
CSS and JSON LS is terminated a moment after initialization

### ISSUE THREAD

**Issue by mniewrzal** [eclipselabs/eclipse-language-service#98]
I'm opening CSS file and all operations are executed (initialization, symbols, diagnostics) but after 2-3 seconds console view is showing that process is terminated. If I will do any move (context menu, hover) LS is spawned correctly but situation is the same and after a moment server is terminated. Interesting is that I don't have such problem with PHP LS which I'm testing also.

**Comment by mickaelistria** [comment]
How are you interacting with the PHP LS? With stdio also or are you using other kinds of streams?

**Comment by mniewrzal** [comment]
Only stdio.

**Comment by mniewrzal** [comment]
I traced it. Problem was on my side, I'm using dummy process id for initialization. Looks that css ans json servers are checking this. I'm closing this issue. Sorry for noise.
